server:
  port: 5555
management:
  endpoints:
    web:
      exposure:
        include: '"*"'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
zuul:
  ignored-services:
  routes:
    microservice1: /ms1/**
    microservice2: /ms2/**


